namespace: ci-cd-demo

backend:
  image:
    repository: ecom-backend
    tag: 25
  port: 5000
  env:
    GOOGLE_CLIENT_ID: "dummy-client-id"
    GOOGLE_CLIENT_SECRET: "dummy-client-secret"
    GOOGLE_CALLBACK_URL: "http://localhost:30007/auth/google/callback"

frontend:
  image:
    repository: ecom-frontend
    tag: 25
  port: 3000
  nodePort: 30007

